print(f"Nothing\nwill work\nunless you do")
print("_______________________")
print('Anyone who\n\tstops\n\tlearning is old,\n\twhether at twenty or eighty"\n\tHenry Ford"')
print("_______________________")
tab = "\t"
print(f"\n{tab}Happiness\n{tab * 2}is\n{tab * 3}not\n{tab * 4}the\n{tab * 5}key\n{tab * 6}to\n{tab * 7}success.")
print("_______________________")
print("*"*8)
print("*Привіт*")
print("*"*8)
print("_______________________")
print("   /\\")
print("  /  \\")
print(" /    \\")
print("/______\\")
